refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {l} {M} :{m}{n}"
  requests:
    kind: rolling_file
    path: "logs/requests.log"
    encoder:
      kind: json
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: '{0}/requests.log.{{}}'
        base: 1
        count: 5
        pattern: "logs/rolling{}.log"
root:
  level: info
  appenders:
    # - stdout
    - requests
